Repository amacneil/dbmate, pull requests merged in 2023-11, with the labels that each got.

#495 Add line/column/position details to Postgres migration/rollback query error messages
  pkg/dbmate/db.go
  pkg/dbmate/db_test.go
  pkg/dbmate/driver.go
  pkg/driver/clickhouse/clickhouse.go
  pkg/driver/mysql/mysql.go
  pkg/driver/postgres/postgres.go
  pkg/driver/sqlite/sqlite.go
Labels: feature request, needs review

#496 fix/correctly parse crlf line endings
  pkg/dbmate/db_test.go
  pkg/dbmate/migration.go
  pkg/dbmate/migration_test.go
Labels: bug

#498 fix: typo
  README.md
Labels: bug

#491 support --env-file CLI option (#274)
  README.md
  fixtures/loadEnvFiles/.env
  fixtures/loadEnvFiles/.gitignore
  fixtures/loadEnvFiles/first.txt
  fixtures/loadEnvFiles/invalid.txt
  fixtures/loadEnvFiles/second.txt
  main.go
  main_test.go
Labels: feature request

#499 Make appending to FLAGS possible when invoking make.
  Makefile
Labels: feature request
